### ISSUE TITLE
[6.1-> 6.2, rhel7] customerdb upgrade failed at test satellite step after restoring db and before initiating upgrade

### ISSUE THREAD

**Issue by sghai** [RedHatSatellite/satellite-clone#209]
```
TASK [satellite-clone : Run installer upgrade (satellite 6.2 only)] ************
Wednesday 26 July 2017  08:17:29 -0400 (0:05:00.061)       0:42:04.461 ******** 
skipping: [SAT_SERVER]

TASK [satellite-clone : Test Satellite] ****************************************
Wednesday 26 July 2017  08:17:29 -0400 (0:00:00.031)       0:42:04.492 ******** 
fatal: [SAT_SERVER]: FAILED! => {"changed": true, "cmd": ["hammer", "ping"], "delta": "0:00:05.172290", "end": "2017-07-26 14:17:39.080979", "failed": true, "rc": 1, "start": "2017-07-26 14:17:33.908689", "stderr": "", "stderr_lines": [], "stdout": "candlepin:      \n    Status:          FAIL\n    Server Response: Message: 404 Resource Not Found\ncandlepin_auth: \n    Status:          FAIL\n    Server Response: Message: Katello::Resources::Candlepin::CandlepinPing: 404 Resource Not Found  (GET /candlepin/status)\npulp:           \n    Status:          ok\n    Server Response: Duration: 48ms\nelasticsearch:  \n    Status:          ok\n    Server Response: Duration: 29ms\nforeman_tasks:  \n    Status:          ok\n    Server Response: Duration: 1ms", "stdout_lines": ["candlepin:      ", "    Status:          FAIL", "    Server Response: Message: 404 Resource Not Found", "candlepin_auth: ", "    Status:          FAIL", "    Server Response: Message: Katello::Resources::Candlepin::CandlepinPing: 404 Resource Not Found  (GET /candlepin/status)", "pulp:           ", "    Status:          ok", "    Server Response: Duration: 48ms", "elasticsearch:  ", "    Status:          ok", "    Server Response: Duration: 29ms", "foreman_tasks:  ", "    Status:          ok", "    Server Response: Duration: 1ms"]}

cmd: hammer ping

start: 2017-07-26 14:17:33.908689

end: 2017-07-26 14:17:39.080979

delta: 0:00:05.172290

stdout: candlepin:      
    Status:          FAIL
    Server Response: Message: 404 Resource Not Found
candlepin_auth: 
    Status:          FAIL
    Server Response: Message: Katello::Resources::Candlepin::CandlepinPing: 404 Resource Not Found  (GET /candlepin/status)
pulp:           
    Status:          ok
    Server Response: Duration: 48ms
elasticsearch:  
    Status:          ok
    Server Response: Duration: 29ms
foreman_tasks:  
    Status:          ok
    Server Response: Duration: 1ms
	to retry, use: --limit @/home/jenkins/workspace/satellite6_db_upgrade_migrate/satellite-clone/satellite-clone-playbook.retry

```

Please note it is appearing while upgrading 6.1 -> 6.2 on rhel6 and using standard backup without pulp data and w/ 1.1.1 release version

**Comment by sghai** [comment]
I tried same DB couple of times w/ earlier 6.2 releases and never found this issue. Its a new issue w/ latest 6.2 compose.

**Comment by johnpmitsch** [comment]
NOTE: Could be fixed in newer satellite builds

**Comment by sthirugn** [comment]
this could be https://access.redhat.com/errata/RHBA-2017:2421? @sghai can you try again?

**Comment by sghai** [comment]
yeah.. will try.

**Comment by sghai** [comment]
w/ recent 6.2.z compose, I hit the same issue again. will investigate and share more info.

**Comment by johnpmitsch** [comment]
@sghai do you mind privately sending me the backup you used for this?

**Comment by sghai** [comment]
@johnpmitsch : yeah sure. will share the link.

**Comment by stuarta** [comment]
I've hit this trying to restore a 6.1 backup. Turns out it's the selinux file contexts on candlepin which prevent candlepin from starting correctly.
`# restorecon -Rv /var/lib/candlepin/
restorecon reset /var/lib/candlepin context system_u:object_r:var_lib_t:s0->system_u:object_r:candlepin_var_lib_t:s0
restorecon reset /var/lib/candlepin/cpdb_done context system_u:object_r:var_lib_t:s0->system_u:object_r:candlepin_var_lib_t:s0
restorecon reset /var/lib/candlepin/hornetq context system_u:object_r:var_lib_t:s0->system_u:object_r:candlepin_var_lib_t:s0
restorecon reset /var/lib/candlepin/hornetq/journal context system_u:object_r:var_lib_t:s0->system_u:object_r:candlepin_var_lib_t:s0
restorecon reset /var/lib/candlepin/hornetq/journal/server.lock context system_u:object_r:var_lib_t:s0->system_u:object_r:candlepin_var_lib_t:s0
restorecon reset /var/lib/candlepin/hornetq/journal/hornetq-data-662.hq context system_u:object_r:tomcat_var_lib_t:s0->system_u:object_r:candlepin_var_lib_t:s0
restorecon reset /var/lib/candlepin/hornetq/journal/hornetq-data-663.hq context system_u:object_r:tomcat_var_lib_t:s0->system_u:object_r:candlepin_var_lib_t:s0
restorecon reset /var/lib/candlepin/hornetq/journal/hornetq-data-755.hq context system_u:object_r:tomcat_var_lib_t:s0->system_u:object_r:candlepin_var_lib_t:s0
restorecon reset /var/lib/candlepin/hornetq/journal/hornetq-data-756.hq context system_u:object_r:tomcat_var_lib_t:s0->system_u:object_r:candlepin_var_lib_t:s0
restorecon reset /var/lib/candlepin/hornetq/journal/hornetq-data-757.hq context system_u:object_r:tomcat_var_lib_t:s0->system_u:object_r:candlepin_var_lib_t:s0
restorecon reset /var/lib/candlepin/hornetq/bindings context system_u:object_r:var_lib_t:s0->system_u:object_r:candlepin_var_lib_t:s0
restorecon reset /var/lib/candlepin/hornetq/bindings/hornetq-bindings-1.bindings context system_u:object_r:var_lib_t:s0->system_u:object_r:candlepin_var_lib_t:s0
restorecon reset /var/lib/candlepin/hornetq/bindings/hornetq-bindings-2.bindings context system_u:object_r:var_lib_t:s0->system_u:object_r:candlepin_var_lib_t:s0
restorecon reset /var/lib/candlepin/hornetq/largemsgs context system_u:object_r:var_lib_t:s0->system_u:object_r:candlepin_var_lib_t:s0
restorecon reset /var/lib/candlepin/hornetq/paging context system_u:object_r:tomcat_var_lib_t:s0->system_u:object_r:candlepin_var_lib_t:s0
restorecon reset /var/lib/candlepin/hornetq/paging/5bf23ac2-5a7a-11e6-9b92-49dd33f0765a context system_u:object_r:tomcat_var_lib_t:s0->system_u:object_r:candlepin_var_lib_t:s0
restorecon reset /var/lib/candlepin/hornetq/paging/5bf23ac2-5a7a-11e6-9b92-49dd33f0765a/address.txt context system_u:object_r:tomcat_var_lib_t:s0->system_u:object_r:candlepin_var_lib_t:s0
restorecon reset /var/lib/candlepin/hornetq/paging/7b6c5367-9d9a-11e6-b95a-f9b48fa2da0f context system_u:object_r:tomcat_var_lib_t:s0->system_u:object_r:candlepin_var_lib_t:s0
restorecon reset /var/lib/candlepin/hornetq/paging/7b6c5367-9d9a-11e6-b95a-f9b48fa2da0f/address.txt context system_u:object_r:tomcat_var_lib_t:s0->system_u:object_r:candlepin_var_lib_t:s0
restorecon reset /var/lib/candlepin/hornetq/paging/151be750-bad1-11e6-bc24-b982ce4fb330 context system_u:object_r:tomcat_var_lib_t:s0->system_u:object_r:candlepin_var_lib_t:s0
restorecon reset /var/lib/candlepin/hornetq/paging/151be750-bad1-11e6-bc24-b982ce4fb330/address.txt context system_u:object_r:tomcat_var_lib_t:s0->system_u:object_r:candlepin_var_lib_t:s0
restorecon reset /var/lib/candlepin/hornetq/paging/af340ff7-cfdf-11e6-b296-399c357d9c6f context system_u:object_r:tomcat_var_lib_t:s0->system_u:object_r:candlepin_var_lib_t:s0
restorecon reset /var/lib/candlepin/hornetq/paging/af340ff7-cfdf-11e6-b296-399c357d9c6f/address.txt context system_u:object_r:tomcat_var_lib_t:s0->system_u:object_r:candlepin_var_lib_t:s0
restorecon reset /var/lib/candlepin/hornetq/paging/87ad68ea-d992-11e6-973c-cf6d138b065b context system_u:object_r:tomcat_var_lib_t:s0->system_u:object_r:candlepin_var_lib_t:s0
restorecon reset /var/lib/candlepin/hornetq/paging/87ad68ea-d992-11e6-973c-cf6d138b065b/address.txt context system_u:object_r:tomcat_var_lib_t:s0->system_u:object_r:candlepin_var_lib_t:s0
restorecon reset /var/lib/candlepin/hornetq/paging/e1c2932f-2f6f-11e7-b2c5-d14acd8eef4a context system_u:object_r:tomcat_var_lib_t:s0->system_u:object_r:candlepin_var_lib_t:s0
restorecon reset /var/lib/candlepin/hornetq/paging/e1c2932f-2f6f-11e7-b2c5-d14acd8eef4a/address.txt context system_u:object_r:tomcat_var_lib_t:s0->system_u:object_r:candlepin_var_lib_t:s0
restorecon reset /var/lib/candlepin/hornetq/paging/da3b6762-99f6-11e7-9f91-4b9e67d53653 context system_u:object_r:tomcat_var_lib_t:s0->system_u:object_r:candlepin_var_lib_t:s0
restorecon reset /var/lib/candlepin/hornetq/paging/da3b6762-99f6-11e7-9f91-4b9e67d53653/address.txt context system_u:object_r:tomcat_var_lib_t:s0->system_u:object_r:candlepin_var_lib_t:s0
restorecon reset /var/lib/candlepin/cpinit_done context system_u:object_r:var_lib_t:s0->system_u:object_r:candlepin_var_lib_t:s0
restorecon reset /var/lib/candlepin/candlepin-crl.crl context system_u:object_r:var_lib_t:s0->system_u:object_r:candlepin_var_lib_t:s0`

**Comment by evgeni** [comment]
6.1 and 6.2 aren't supported for a while now, closing
